import type { Factory, Style, Order, Quote, Project, DashboardMetrics, Milestone, CriticalItem } from "./types"

export const factories: Factory[] = [
  {
    id: "maeknit",
    name: "MAEKNIT",
    location: "United States",
    country: "US",
    rating: 4.8,
    moq: 1,
    leadTime: "4-6 weeks",
    specialty: "Premium Knits",
    quality: "Premium Quality",
  },
  {
    id: "factory-b",
    name: "Factory B",
    location: "Turkey",
    country: "TR",
    rating: 4.2,
    moq: 5,
    leadTime: "3-4 weeks",
    specialty: "Cotton Blends",
    quality: "Standard Quality",
  },
  {
    id: "factory-c",
    name: "Factory C",
    location: "Peru",
    country: "PE",
    rating: 4.0,
    moq: 15,
    leadTime: "5-7 weeks",
    specialty: "Alpaca Wool",
    quality: "Standard Quality",
  },
  {
    id: "factory-d",
    name: "Factory D",
    location: "United Kingdom",
    country: "GB",
    rating: 4.5,
    moq: 10,
    leadTime: "6-8 weeks",
    specialty: "Luxury Knits",
    quality: "Premium Quality",
  },
  {
    id: "factory-e",
    name: "Factory E",
    location: "Bulgaria",
    country: "BG",
    rating: 3.9,
    moq: 400,
    leadTime: "25 days",
    specialty: "Cotton Knits",
    quality: "Standard Quality",
  },
  {
    id: "factory-f",
    name: "Factory F",
    location: "China",
    country: "CN",
    rating: 3.5,
    moq: 1000,
    leadTime: "35 days",
    specialty: "Mass Production",
    quality: "Economy Quality",
  },
]

export const styles: Style[] = [
  {
    id: "mss-001",
    name: "Mohair Striped Sweater",
    image: "/assets/5.png",
    code: "MSS-2025-001",
    category: "Knitwear",
    season: "Fall/Winter 2025",
    targetMarket: "Premium Casual",
    composition: "100% Merino Wool",
    weight: "12GG",
    fit: "Regular Fit",
    careInstructions: "Hand wash cold, lay flat to dry",
    status: "Ready for Production",
    progress: 75,
    stage: "In Production",
    eta: "Mar 15",
    colorways: 5,
    sizes: 6,
  },
  {
    id: "cd-002",
    name: "Cardigan",
    image: "/assets/4.png",
    code: "CDG-002",
    category: "Knitwear",
    season: "Fall/Winter 2025",
    targetMarket: "Premium Casual",
    composition: "80% Cotton, 20% Cashmere",
    weight: "7GG",
    fit: "Relaxed Fit",
    careInstructions: "Dry clean only",
    status: "Materials Purchased",
    progress: 25,
    stage: "Materials",
    eta: "Apr 2",
    colorways: 3,
    sizes: 5,
  },
  {
    id: "av-003",
    name: "Argyle Vest",
    image: "/assets/2.png",
    code: "AVT-003",
    category: "Knitwear",
    season: "Fall/Winter 2025",
    targetMarket: "Classic",
    composition: "100% Wool",
    weight: "5GG",
    fit: "Slim Fit",
    careInstructions: "Hand wash cold",
    status: "Quality Control",
    progress: 85,
    stage: "Quality Control",
    eta: "Feb 28",
    colorways: 4,
    sizes: 4,
  },
  {
    id: "sc-004",
    name: "Scarf",
    code: "SCF-004",
    category: "Accessories",
    image: "/assets/7.webp",
    season: "Fall/Winter 2025",
    targetMarket: "Premium",
    composition: "100% Cashmere",
    weight: "2GG",
    fit: "One Size",
    careInstructions: "Dry clean only",
    status: "Completed",
    progress: 100,
    stage: "On the Way!",
    eta: "Ready",
    colorways: 6,
    sizes: 1,
  },
  {
    id: "pl-005",
    name: "Polo",
    code: "PLO-005",
    image: "/assets/3.png",
    category: "Knitwear",
    season: "Spring/Summer 2025",
    targetMarket: "Casual",
    composition: "100% Pima Cotton",
    weight: "12GG",
    fit: "Regular Fit",
    careInstructions: "Machine wash cold",
    status: "Finishing",
    progress: 80,
    stage: "Finishing",
    eta: "Mar 8",
    colorways: 7,
    sizes: 6,
  },
  {
    id: "mrn-006",
    name: "4x1 Merino Top",
    image: "/assets/6.jpg",
    code: "MRN-006",
    category: "Knitwear",
    season: "Spring/Summer 2025",
    targetMarket: "Athletic",
    composition: "100% Merino Wool",
    weight: "14GG",
    fit: "Athletic Fit",
    careInstructions: "Machine wash cold",
    status: "Materials",
    progress: 33,
    stage: "Materials",
    eta: "Apr 12",
    colorways: 4,
    sizes: 5,
  },
  {
    id: "bne-007",
    name: "Beanie",
    image: "/assets/1.png",
    code: "BNE-007",
    category: "Accessories",
    season: "Fall/Winter 2025",
    targetMarket: "Casual",
    composition: "100% Acrylic",
    weight: "5GG",
    fit: "One Size",
    careInstructions: "Machine wash warm",
    status: "Shipping",
    progress: 92,
    stage: "On the Way!",
    eta: "Feb 25",
    colorways: 8,
    sizes: 1,
  },
  {
    id: "tnk-008",
    name: "Mohair Cropped Cardigan",
    code: "MCC-008",
    image: "/assets/8.png",
    category: "Knitwear",
    season: "Fall/Winter 2025",
    targetMarket: "Premium",
    composition: "100% Merino Wool",
    weight: "12GG",
    fit: "Slim Fit",
    careInstructions: "Hand wash cold",
    status: "In Production",
    progress: 50,
    stage: "In Production",
    eta: "Mar 20",
    colorways: 5,
    sizes: 6,
  },
]

export const orders: Order[] = [
  {
    id: "order-1",
    orderId: "1001",
    styleId: "vc-001",
    styleName: "Vintage Crewneck",
    factoryId: "maeknit",
    factoryName: "MAEKNIT",
    totalUnits: 500,
    totalValue: 12500,
    status: "In Production",
    moq: 100,
    items: [
      { color: "Navy", size: "S", units: 50, pricePerUnit: 25.0, total: 1250 },
      { color: "Navy", size: "M", units: 75, pricePerUnit: 25.0, total: 1875 },
      { color: "Navy", size: "L", units: 100, pricePerUnit: 25.0, total: 2500 },
      { color: "Charcoal", size: "M", units: 125, pricePerUnit: 25.0, total: 3125 },
      { color: "Charcoal", size: "L", units: 75, pricePerUnit: 25.0, total: 1875 },
      { color: "Cream", size: "L", units: 75, pricePerUnit: 25.0, total: 1875 },
    ],
  },
  {
    id: "order-2",
    orderId: "1002",
    styleId: "cd-002",
    styleName: "Cardigan",
    factoryId: "factory-b",
    factoryName: "Factory B",
    totalUnits: 400,
    totalValue: 9200,
    status: "Finishing",
    moq: 200,
    items: [
      { color: "Camel", size: "S", units: 60, pricePerUnit: 23.0, total: 1380 },
      { color: "Camel", size: "M", units: 80, pricePerUnit: 23.0, total: 1840 },
      { color: "Navy", size: "M", units: 100, pricePerUnit: 23.0, total: 2300 },
      { color: "Navy", size: "L", units: 90, pricePerUnit: 23.0, total: 2070 },
      { color: "Burgundy", size: "L", units: 70, pricePerUnit: 23.0, total: 1610 },
    ],
  },
  {
    id: "order-3",
    orderId: "1003",
    styleId: "av-003",
    styleName: "Argyle Vest",
    factoryId: "factory-c",
    factoryName: "Factory C",
    image_url: "/assets/1.png", 
    totalUnits: 250,
    totalValue: 5250,
    status: "On the Way!",
    moq: 150,
    items: [
      { color: "Navy/Gray", size: "S", units: 40, pricePerUnit: 21.0, total: 840 },
      { color: "Navy/Gray", size: "M", units: 70, pricePerUnit: 21.0, total: 1470 },
      { color: "Navy/Gray", size: "L", units: 60, pricePerUnit: 21.0, total: 1260 },
      { color: "Burgundy/Cream", size: "M", units: 50, pricePerUnit: 21.0, total: 1050 },
      { color: "Burgundy/Cream", size: "L", units: 30, pricePerUnit: 21.0, total: 630 },
    ],
  },
]

export const quotes: Quote[] = [
  {
    id: "quote-1",
    factoryId: "maeknit",
    factory: factories[0],
    unitPrice: 24.5,
    moq: 200,
    leadTime: "34 days",
    total: 12250,
  },
  {
    id: "quote-2",
    factoryId: "factory-b",
    factory: factories[1],
    unitPrice: 18.75,
    moq: 300,
    leadTime: "21 days",
    total: 9375,
    selected: false,
  },
  {
    id: "quote-3",
    factoryId: "factory-c",
    factory: factories[2],
    unitPrice: 16.2,
    moq: 500,
    leadTime: "28 days",
    total: 8100,
  },
  {
    id: "quote-4",
    factoryId: "factory-d",
    factory: factories[3],
    unitPrice: 22.8,
    moq: 250,
    leadTime: "18 days",
    total: 11400,
  },
  {
    id: "quote-5",
    factoryId: "factory-e",
    factory: factories[4],
    unitPrice: 19.6,
    moq: 400,
    leadTime: "25 days",
    total: 9800,
  },
  {
    id: "quote-6",
    factoryId: "factory-f",
    factory: factories[5],
    unitPrice: 12.3,
    moq: 1000,
    leadTime: "35 days",
    total: 6150,
  },
]

export const projects: Project[] = [
  {
    id: "proj-1",
    name: "Vintage Crewneck",
    orderId: "1001",
    factoryName: "MAEKNIT",
    expectedDate: "Mar 15",
    status: "In Production",
    stages: [
      { name: "Materials", completed: true },
      { name: "Transit", completed: true },
      { name: "Production", completed: false, current: true },
      { name: "Finishing", completed: false },
      { name: "QC", completed: false },
      { name: "Shipping", completed: false },
    ],
  },
  {
    id: "proj-2",
    name: "Cardigan",
    orderId: "1002",
    factoryName: "Factory B",
    expectedDate: "Apr 2",
    status: "Transit",
    stages: [
      { name: "Materials", completed: true },
      { name: "Transit", completed: false, current: true },
      { name: "Production", completed: false },
      { name: "Finishing", completed: false },
      { name: "QC", completed: false },
      { name: "Shipping", completed: false },
    ],
  },
  {
    id: "proj-3",
    name: "Argyle Vest",
    orderId: "1003",
    factoryName: "Factory C",
    expectedDate: "Mar 22",
    status: "Quality Control",
    stages: [
      { name: "Materials", completed: true },
      { name: "Transit", completed: true },
      { name: "Production", completed: true },
      { name: "Finishing", completed: true },
      { name: "QC", completed: false, current: true },
      { name: "Shipping", completed: false },
    ],
  },
  {
    id: "proj-4",
    name: "Scarf",
    orderId: "1004",
    factoryName: "Factory D",
    expectedDate: "Apr 8",
    status: "Transit",
    stages: [
      { name: "Materials", completed: true },
      { name: "Transit", completed: false, current: true },
      { name: "Production", completed: false },
      { name: "Finishing", completed: false },
      { name: "QC", completed: false },
      { name: "Shipping", completed: false },
    ],
  },
  {
    id: "proj-5",
    name: "Polo",
    orderId: "1005",
    factoryName: "Factory E",
    expectedDate: "Mar 25",
    status: "Finishing",
    stages: [
      { name: "Materials", completed: true },
      { name: "Transit", completed: true },
      { name: "Production", completed: true },
      { name: "Finishing", completed: false, current: true },
      { name: "QC", completed: false },
      { name: "Shipping", completed: false },
    ],
  },
  {
    id: "proj-6",
    name: "4x1 Merino Top",
    orderId: "1006",
    factoryName: "Factory F",
    expectedDate: "Mar 12",
    status: "Shipping",
    stages: [
      { name: "Materials", completed: true },
      { name: "Transit", completed: true },
      { name: "Production", completed: true },
      { name: "Finishing", completed: true },
      { name: "QC", completed: true },
      { name: "Shipping", completed: false, current: true },
    ],
  },
]

export const dashboardMetrics: DashboardMetrics = {
  toSend: 7,
  quotesPending: 8,
  ordersInProgress: 15,
  shipments: 6,
}

export const upcomingMilestones: Milestone[] = [
  {
    id: "milestone-1",
    name: "Vintage Crewneck Finishing",
    expectedDate: "Mar 15, 2025",
    daysUntil: 5,
  },
  {
    id: "milestone-2",
    name: "Polo Quality Control",
    expectedDate: "Mar 20, 2025",
    daysUntil: 10,
  },
  {
    id: "milestone-3",
    name: "Argyle Vest Shipment",
    expectedDate: "Mar 22, 2025",
    daysUntil: 12,
  },
]

export const criticalItems: CriticalItem[] = [
  {
    id: "critical-1",
    name: "Cardigan Materials Delay",
    factory: "Factory B",
    description: "3 days behind",
  },
  {
    id: "critical-2",
    name: "Scarf Quality Check",
    factory: "Factory D",
    description: "Pending approval",
  },
]
